### ISSUE TITLE
[Bug] - Triggers that are not scheduled do not get seen as failures 

### ISSUE THREAD

**Issue by u-n-i-c-o-rn** [z1pti3/jimi#197] opened 2021-08-26 10:48 UTC
If a trigger exists but does not get scheduled the platform does not identify this and therefore a failure is not raised.

**Comment by z1pti3** [comment] 2021-08-29 13:24
Caused by a bug loading trigger classes - this is now fixed in the latest dev version

**Closed as completed by z1pti3** 2021-08-29 13:24 UTC
Labels: bug
